server:
  port: 9090

spring:
  datasource:
    generate-unique-name: false
    name: Employees
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect